-- Migration 063: Clean up rogue opening balance entries created from sales invoices
-- and ensure customer opening balances cannot be corrupted by sales operations.
BEGIN;

-- 1. Identify customers who had an opening balance injected by sales invoice operations
-- (marked by descriptions 'Opening Balance entered on invoice for %' or 'Opening Balance recorded on invoice for %')
-- where the customer already had prior sales or where the opening balance matched the invoice previous balance.
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN (
    SELECT DISTINCT le.customer_id, le.debit AS rogue_ob
    FROM ledger_entries le
    JOIN customers c ON c.id = le.customer_id
    WHERE le.entry_type = 'OPENING_BALANCE'
      AND (
        le.description LIKE 'Opening Balance entered on invoice for %' 
        OR le.description LIKE 'Opening Balance recorded on invoice for %'
      )
      AND c.opening_balance = le.debit
      AND (SELECT COUNT(*) FROM sales s WHERE s.customer_id = le.customer_id) > 0
  ) LOOP
    -- Reset opening balance to 0.00 if it was artificially set from an invoice
    UPDATE customers 
    SET opening_balance = 0.00
    WHERE id = r.customer_id AND opening_balance = r.rogue_ob;

    -- Delete any unneeded allocations to this fake opening balance
    DELETE FROM payment_allocations 
    WHERE customer_id = r.customer_id 
      AND allocation_type = 'opening_balance';
  END LOOP;
END $$;

-- 2. Remove all rogue OPENING_BALANCE ledger_entries generated by sales creation/editing
DELETE FROM ledger_entries
WHERE entry_type = 'OPENING_BALANCE'
  AND (
    description LIKE 'Opening Balance entered on invoice for %' 
    OR description LIKE 'Opening Balance recorded on invoice for %'
  );

-- 3. Re-synchronize current_balance for all customers
UPDATE customers c
SET current_balance = (
  COALESCE(c.opening_balance, 0)
  + COALESCE((SELECT SUM(COALESCE(NULLIF(s.current_invoice_total, 0), s.total_amount)) FROM sales s WHERE s.customer_id = c.id), 0)
  - COALESCE((SELECT SUM(pm.amount) FROM payments pm WHERE pm.customer_id = c.id AND pm.reversed_at IS NULL AND COALESCE(pm.payment_mode, '') != 'credit_note'), 0)
  - COALESCE((SELECT SUM(cn.amount) FROM credit_notes cn WHERE cn.customer_id = c.id AND cn.status != 'cancelled'), 0)
);

COMMIT;
